
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhnaywrgoeibqopflbfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZobmF5d3Jnb2VpYnFvcGZsYmZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NjQyMDMsImV4cCI6MjA2MzM0MDIwM30.fFnJDfogx7BcgIbFj2KvOdpTlj5O9gqPxYWwWZZINrw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
